routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function (){
    return view('index');
});
//Route User Import
Route::prefix('users')->name('users.')->group(function ($router){
    $router->get('import', 'ImportExcelController@index')->name('index');
    $router->post('import', 'ImportExcelController@import')->name('import');
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = ['name'];

    public function users()
    {
        return $this->belongsToMany(User::class,'role_user');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'city', 'country' ,'address','gender',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class,'role_user');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ImportExcelController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UploadExcelRequest;
use App\Imports\MultiSheetImport;
use App\User;


class ImportExcelController extends Controller
{
    public function index()
    {
        $users = User::with('roles')->orderBy('id','DESC')->get();
        return view('import.users',compact('users'));
    }


    public function import(UploadExcelRequest $request)
    {
        $path = $request->file('file')->getRealPath();
        $import = new MultiSheetImport();
        $import->import($path);


        return  back()->withStatus('Import Success File Excel');
    }

}

resources/views/errors.blade.php
@if(count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session('status'))
    <div class="alert alert-success">
        {{  session('status') }}
    </div>
@endif

resources/views/import/form-imports.blade.php
<form action="{{ route($routeName) }}" method="POST" enctype="multipart/form-data">
    @csrf

    <div class="form-group">
        <table class="table">
            <tr>
                <td width="30%" align="left">
                    <label for="">Please Select a File Excel</label>
                </td>
                <td width="40%" align="center">
                    <input type="file" name="file">
                </td>
                <td width="30%" align="right">
                    <input class="btn btn-primary" type="submit" name="upload" value="Import">
                </td>

            </tr>
        </table>
    </div>
</form>

resources/views/import/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Import Excel</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
    @yield('content')
</body>
</html>

resources/views/import/users.blade.php
@extends('import.master')
@section('content')
    <div class="container">
    <h3 align="center">Import  File User  Excel </h3>
    @include('errors')
    @include('import.form-imports',['routeName' => 'users.import'])
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">name</th>
            <th scope="col">city</th>
            <th scope="col">country</th>
            <th scope="col">gender</th>
            <th scope="col">address</th>
            <th scope="col">roles</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <th scope="row">{{$user->id}}</th>
                <td>{{$user->name}}</td>
                <td>{{$user->city}}</td>
                <td>{{$user->country}}</td>
                <td>{{$user->gender}}</td>
                <td>{{$user->address}}</td>
                <td>
                    @foreach ($user->roles as $role)
                        | {{$role->name}} |
                    @endforeach
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/index.blade.php
@extends('import.master')
@section('content')
    <div class="container">
        <h3 align="center">Import File </h3>

        <div align="center">
            <a href="{{ route('users.index') }}" class="btn btn-primary">Import Excel</a>
        </div>
    </div>
@endsection